### ISSUE TITLE
-s suricata command not working

### ISSUE THREAD

**Issue by dyxwxjdy** [3CORESec/S2AN#2]
Hi , I try to map Suricata rules to attck with following command:
S2AN.exe -s -d rules\ -o output\
but it returns "Problem writing to file: Sequence contains no elements"

**Comment by 0xtf** [comment]
Hi @dyxwxjdy. Sorry for the delay in getting back to you. 

Did the signatures you were mapping had the appropriate tags in them? At the very least, `mitre_technique_id` is required. If the signatures has the tag but somehow S2AN failed, please send us the signature so we can look into it. 

If you want to avoid pasting the signature in a public forum you can also e-mail it to me: my github username @3coresec.com.

**Comment by dyxwxjdy** [comment]
already solve it ,thank you!
